- name: Download blackbox-exporter
  local_action: get_url
    url="{{ blackbox_download_url }}"
    dest="{{ blackbox_download_dir }}"
    checksum="{{ blackbox_download_checksum }}"

- name: Create folder to unpack blackbox-exporter
  local_action: file
    path="{{ blackbox_extract_folder }}"
    state="directory"

- name: Unpack blackbox-exporter
  local_action: command tar -xf "{{ blackbox_download_dir }}" -C "{{ blackbox_extract_folder }}" --strip-components=1 --overwrite

- name: Ensure that all necessary bindings for python are installed (only for Fedora)
  become: true
  dnf:
    state: latest
    name: "{{ item }}"
  with_items:
    - libselinux-python
    - python-firewall
  when: ansible_distribution == "Fedora"

- name: Create Prometheus user
  become: true
  user: 
    name: "{{ blackbox_user  }}"
    shell: "/sbin/nologin"
    home: "{{ blackbox_home }}"
    state: present

- name: Create blackbox-exporter bin directory
  become: true
  file:
    path: "{{ blackbox_bin_dir }}"
    state: directory

- name: Copy blackbox-exporter to remote host
  become: true
  copy:
    src: "{{ blackbox_extract_folder }}/"
    dest: "{{ blackbox_bin_dir }}"
    owner: "root"
    group:  "root"
    mode: "u=rwx,g=rwx,o=r"
  notify: restart blackbox-exporter service

- name: Create blackbox-exporter configuration directory
  become: true
  file:
    path: "{{ blackbox_conf_dir }}"
    state: directory
    owner: "{{ blackbox_user }}"
    mode: "u=rwx,g=rwx,o=r"
  notify: restart blackbox-exporter service

- name: Copy blackbox-exporter configuration
  become: True
  template:
    src: "blackbox-exporter.yml.j2"
    dest: "{{ blackbox_conf_dir }}/blackbox-exporter.yml"
    owner: "{{ blackbox_user }}"
    group: "{{ blackbox_user }}"
    mode: "u=rw,g=r,o=r"
  notify: restart blackbox-exporter service
  tags: blackbox_update_config

- name: Copy blackbox-exporter service definition
  become: true
  template:
    src: "blackbox-exporter.service.j2"
    dest: "{{ blackbox_service_dir }}/{{ blackbox_service_name }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  tags: blackbox_update_config

- name: Reload blackbox-exporter service definition
  become: true
  systemd:
    name: "{{ blackbox_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: yes
  tags: blackbox_update_config

- name: Enable firewall ports for the blackbox-exporter service
  become: true
  ignore_errors: true
  firewalld:
    immediate: true
    port: 9115/tcp
    permanent: true
    state: enabled
  notify: restart blackbox-exporter service
